config/routes.rb
SocialNetwork::Application.routes.draw do
  post  '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'users#show'
  
  resources :posts
  get "post" => 'posts#destroy'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :images, only: [:create, :destroy]
  
  resources :users do 
    delete 'friend' => 'friends#destroy'
    put 'friend' => 'friends#update'
    resources :friends, only: [:create, :destroy]
    resource :profiles  
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :author, :class_name => "User"
  belongs_to :commentable, :polymorphic => true
  has_many :comments, :as => :commentable
  has_many :likes, :as => :likeable
  
  validates :content, length: { minimum: 2 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_commented, :only => [:create]
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = @commented.comments.new(:author_id => current_user.id, :content => params[:comment][:content])
    if @comment.save
      flash[:success] = "Comment Posted!"
      redirect_to user_path(current_user)
    else
      render new_comment_path
    end
  end
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:error] = "Comment destroyed"
      redirect_to session.delete(:return_to)
    end
  end
  
  #perhaps whitelist before this constantize call
  private
  def find_commented
    klass = params[:commentable_type].capitalize.constantize
    @commented = klass.find(params[:commentable_id])
  end
  def comment_params
    params.require(:comment).permit(:author_id, :content, :commentable_type, :commentable_id) 
  end
end

app/views/comments/new.html.erb
<div class="column-main">
  <div class="column-main-content">
    <h1> Comment for:</h1>
    <%= form_for @comment, :url => comments_path(:commentable_type => params[:commentable_type], :commentable_id => params[:commentable_id], :author_id => current_user.id) do |f| %>
    <%= render 'shared/error_messages', f: @comment %>
      <div class="field">
        <%= f.text_area :content, :size => "50x2" %>
      </div>

     
      <div>
        <%= f.submit %>
      </div>
      <% end %>
  </div>
</div>