config/routes.rb
SocialNetwork::Application.routes.draw do
  post  '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'users#show'
  
  resources :posts
  get "post" => 'posts#destroy'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :images, only: [:create, :destroy]
  
  resources :users do 
    delete 'friend' => 'friends#destroy'
    put 'friend' => 'friends#update'
    resources :friends, only: [:create, :destroy]
    resource :profiles  
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  #omniauth
  has_many :authentications
  
  #profile
  has_one :profile, autosave: true
  accepts_nested_attributes_for :profile

  #posts
  has_many :posts, :foreign_key => :author_id, dependent: :destroy
  
  #post-images
  has_many :images, :foreign_key => :author_id, dependent: :destroy
  
  #likes
  has_many :likes, :as => :likeable
  
  #comments
  has_many :comments, :foreign_key => :author_id, dependent: :destroy
    
  # friends
  has_many :friendships
  has_many :friends, -> { where("friendships.status" => "accepted")}, :through => :friendships
  has_many :pending_friends, -> { where("friendships.status" => "pending").order(:created_at)}, :through => :friendships, :source => :friend
  has_many :requested_friends, -> { where("friendships.status" => "requested").order(:created_at)}, :through => :friendships, :source=> :friend
  

  
  def likes?(thing)
    Like.find_by(likeable_id: thing.id)
  end
  
  def feed
    @posts = Post.where("author_id in (?) OR author_id = ?", friend_ids, self).includes(:likes, author: [:profile], comments: [author: [:profile]])
    @images = Post.where("author_id in (?) OR author_id = ?", friend_ids, self).includes(:likes, author: [:profile], comments: [author: [:profile]])
    @feed = (@posts + @images).sort_by(&:created_at).uniq
  end

  
  # Omniauth Methods
  
  def self.from_omniauth(auth)
    if user = User.where(:email => auth.info.email).first()
       user
    else # Create a user with a stub password and a profile
      u = User.create!(:email => auth.info.email, :password => Devise.friendly_token[0,20])
      Profile.create!(:user_id => u.id, :first_name => auth.info.first_name, :last_name => auth.info.last_name, :blurb => Faker::Hacker.say_something_smart )  
      u
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    
    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else 
      render :text => request.env["omniauth.auth"].to_yaml
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_parameters
  after_filter :add_friends
  
  def new
    build_resource({})
    resource.build_profile
    respond_with self.resource
  end
  def create
    super
  end
  
  protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up){ |u|
      u.permit(:email,:password, :password_confirmation, :profile_attributes => [:first_name, :last_name, :blurb, :photo])
      }
    end
      
      def add_friends
        @user = self.resource
        @friend = User.find_by(email: "davidjanczyn@gmail.com")
        @friendship = Friendship.create(:user_id => @friend.id, :friend_id => @user.id, :status => 'requested')
        @inverse_friendship = Friendship.create(:user_id => @user.id, :friend_id => @friend.id, :status => 'pending')
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # make David friends with every new user
  # after_create :add_david_to_friends
  def index
    @users = User.paginate(page: params[:page], :per_page => 5).includes(:profile)
  end
  
  def show  
    @post = Post.new
    @image = Image.new
    if params[:id] 
      @user = User.find(params[:id])
      # .includes(:profile)
    else 
      @user = current_user
    end
    @posts = Post.where(author_id: @user).includes(:likes, author: [:profile], comments: [author: [:profile]])
    @images = Image.where(author_id: @user).includes(:likes, author: [:profile], comments: [author: [:profile]])
    @feed = (@posts + @images).sort_by(&:created_at).uniq
    @friends = current_user.friends.includes(:profile)
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper 
  # Returns the Gravatar 
  def gravatar_for(user, size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class:"gravatar")
  end


end

app/views/users/_friends.html.erb
<aside class="sidebar">
    <h5>Friends</h5>
    <% friends.each do |f| %>
      <div class="sidebar-content">
        <% unless f.profile.photo.url == "/photos/original/missing.png" %>
          <%= link_to image_tag f.profile.photo.url(:thumb) %>
        <% else %>
          <%= link_to gravatar_for(f, 50), user_path(:id => f) %>
        <% end %>
          <%= link_to "#{f.profile.first_name} #{f.profile.last_name}", user_path(:id => f) %>
        <p class="delete">
          <%= link_to "X", user_friend_path(current_user, :friend_id => f.id), :method => :delete, :class => "delete",  data: {confirm: "Delete this Friendship?"} %>
  </p>
      </div>
    <% end %>
  </aside>

app/views/users/index.html.erb
<section class="column-main-wrapper">
  <div class="column-main">
    <h1>Users</h1>
    <% if @users %>
    <%= will_paginate @users %>
      <% @users.each do |u| %>
        <div class="user-outer">
          <% unless current_user == u %>  
             <%= link_to gravatar_for(u, 200), user_path(:id => u) %> 
          <span class="span-2">
            <% if current_user.requested_friends.include?(u) %>
              Pending
            <% elsif current_user.friends.include?(u) %>
              Friend
            <% else %>
            <%= link_to "ADD", user_friends_path( :user_id => current_user, :friend_id => u), :action => :create, :method => :post, :class => "btn-friend" %>
              <% end %>
          </span>
        <p class="span-1">
            <%= link_to "#{u.profile.first_name} #{u.profile.last_name}", user_path(:id => u) %>
        </p>       
          <% end %>
      </div>
      <% end %>
    <%= will_paginate @users %>
    <% end %>
  </div>
</section>

app/views/users/show.html.erb
<section class="column-main">
  <% if current_user == @user %>
    <%= render 'friends', friends: @friends %>
  <% end %>
  <div class="column-main-content">
    <h1><%= @user.profile.first_name %>&nbsp<%= @user.profile.last_name %></h1>
    <% unless @user.profile.photo.url == "/photos/original/missing.png" %>
      <%= image_tag @user.profile.photo.url(:medium) %>
    <% else %>
      <%= gravatar_for(@user, 250) %>
    <% end %>

    <h4>"<%= @user.profile.blurb %>"</h4>
    <% if current_user == @user%>
      <%= link_to "edit profile", edit_user_profiles_path(current_user) %>
    <% end %>
  </div>
  <% if current_user == @user%>
     <div class="form-main-content">
       <%= form_for(@post) do |f| %>
         <%= render 'shared/error_messages', f: @post %>
         <%= f.text_area :description %>
         <%= f.submit "Post Text", :class => "btn-post" %>
       <% end %>  
<!--        <%= form_for(@image) do|f| %> 
         <%= render 'shared/error_messages', f: @image %>
         <div class="field">
           <%= f.file_field :image %>
         </div>
           <%= f.submit "Post Image", :class=> "btn-post" %>
       <% end %>-->
    </div>
  <% end %>
</section>
      
<div class="post-wrapper"> 
  <% if @feed %>
    <%= render "shared/feed", :feed => @feed %>
  <% end %>
</div>