config/routes.rb
SocialNetwork::Application.routes.draw do
  post  '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'users#show'
  
  resources :posts
  get "post" => 'posts#destroy'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :images, only: [:create, :destroy]
  
  resources :users do 
    delete 'friend' => 'friends#destroy'
    put 'friend' => 'friends#update'
    resources :friends, only: [:create, :destroy]
    resource :profiles  
  end
  
end

app/views/shared/_delete.html.erb
  <p class="delete">
    <%= link_to "X", path.call(f.id), :method => :delete,  data: {confirm: "Are you sure?"} %>
  </p>

app/views/shared/_error_messages.html.erb
<% if f.errors.any? %>
  <div id="error_explanation"> 
    <div class="alert alert-danger">
      The form contains <%= pluralize(f.errors.count, "error") %>.
    </div>
    <ul>
      <% f.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% feed.each do |f| %>
  <article class="post-container clearfix">  
    <div class="post-inner clearfix">
      <div class="post-author">
        <h3><%= link_to "#{f.author.profile.first_name} #{f.author.profile.last_name}", user_path(:id => f.author_id)%></h3><span class="verb">says:</span>
        <% unless f.author.profile.photo.url == "/photos/original/missing.png" %>
          <%= image_tag f.author.profile.photo.url(:thumb) %>
        <% else %>
          <%= gravatar_for(f.author, 75) %>
        <% end %>
      </div>
      <% if f.respond_to? :image%>
        <% if current_user == f.author %>
          <%= render "shared/delete", :path => method(:image_path), :f => f %>
        <% end %> 
        <%= render "shared/image", :i => f %>
      <% else %>
        <% if current_user == f.author %>
          <%= render "shared/delete", :path => method(:post_path), :f => f %>
        <% end %>  
        <%= render "shared/post", :p => f %>
      <% end %>    
    </div>
  </article>
  <% f.comments.each do |c| %>
    <article class="comment-container clearfix">
      <div class="comment-inner clearfix">
        <div class="comment-author">
          <h3><%= link_to "#{c.author.profile.first_name} #{c.author.profile.last_name}", user_path(:id => c.author_id) %></h3>
          <%= gravatar_for(c.author, 75) %>
          <span>comments:</span>
        </div>
        <p class="delete">
        <% if current_user == c.author %>
          <%= link_to "X", comment_path(c.id), :method => :delete,  data: {confirm: "Are you sure?"} %>
        <% end %>
      </p>
        <div class="comment-content">
          <%= c.content %>
        </div>
        <div class="right-tools">
          <% if c.likes.count > 0 %>
            <span class="like-count"><%= pluralize(c.likes.count, "like") %></span>
          <% end %>
          <% if current_user == c.author || current_user.friends.include?(c.author) %>
            <% if current_user.likes?(c) %>
              <%= link_to "Unlike", like_path(:id => 0, :likeable_id => c.id), :method => :delete %>
            <% else %>
              <%= link_to "Like", likes_path(:likeable_id => c.id, :likeable_type => "comment"), :action => :create, :method => :post %>
            <% end %> 
        <% end %>
        </div>
      </div>
    </article>
  <% end %>
<% end %>

app/views/shared/_image.html.erb
<div class="post-content">
  <%= image_tag i.image.url(:medium) %>
</div>
<% if current_user == @user || current_user.friends.include?(@user) %>
  <div class="right-tools">
    <% if i.likes.count > 0 %>
      <span class="like-count"><%= pluralize(i.likes.count, "like") %></span>
    <% end %>
    <% if current_user.likes?(i) %>
      <%= link_to "Unlike", like_path(:id => 0, :likeable_id => i.id), :method => :delete %>
    <% else %>
      <%= link_to "Like", likes_path(:likeable_id => i.id, :likeable_type => "image"), :action => :create, :method => :post %>
    <% end %>  
      <%= link_to "Comment", new_comment_path(:author_id => current_user.id, :commentable_type => "image", :commentable_id => i.id) %>    
  </div>    
<% end %>

app/views/shared/_post.html.erb
<div class="post-content">
  <%= p.description %>
</div>

  <div class="right-tools">
    <% if p.likes.count > 0 %>
      <span class="like-count"><%= pluralize(p.likes.count, "like") %></span>
    <% end %>
    
    <% if current_user == p.author || current_user.friends.include?(p.author) %>
      <% if current_user.likes?(p) %>
        <%= link_to "Unlike", like_path(:id => 0, :likeable_id => p.id), :method => :delete %>
      <% else %>
      <%= link_to "Like", likes_path(:likeable_id => p.id, :likeable_type => "post"), action: "create", method: "Post" %>
      <% end %>  
      <%= link_to "Comment", new_comment_path(:author_id => current_user.id, :commentable_type => "post", :commentable_id => p.id) %>    
    </div>    
  <% end %>