config/routes.rb
SocialNetwork::Application.routes.draw do
  post  '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  root 'users#show'
  
  resources :posts
  get "post" => 'posts#destroy'
  resources :likes, only: [:create, :destroy]
  resources :comments, only: [:new, :create, :destroy]
  resources :images, only: [:create, :destroy]
  
  resources :users do 
    delete 'friend' => 'friends#destroy'
    put 'friend' => 'friends#update'
    resources :friends, only: [:create, :destroy]
    resource :profiles  
  end
  
end

app/views/layouts/_header.html.erb
<header>
  <div id="logo"><%=link_to current_user do %> 
    <i class="fa fa-home fa-2x"></i>
    <% end %>
  </div>
  <% if user_signed_in? %>
  <nav class="nav">
    <ul>
      <li><%= link_to  users_path do %>
        <i class="fa fa-users fa-2x"></i>
      <% end %> </li>
      <li><%= link_to posts_path do %>
        <i class="fa fa-rss-square fa-2x"></i>
        <% end %></li>
      <li><%= render "layouts/notifications", pending_friends: @pending_friends %></li>
      <li><%= link_to destroy_user_session_path, :method => :delete  do %>
        <i class="fa fa-sign-out fa-2x"></i>
        <% end %></li>
    </ul>
  </nav>   
  <% end %>
</header>

app/views/layouts/_notifications.html.erb
<button type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
  <i class="fa fa-bell fa-2x"><div class="<%= 'true' if @pending_friends.size > 0 %>"></div></i>
  
</button>
<ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
  <% pending_friends.each do |p| %>
  <li role="presentation"><b><%= gravatar_for(p, 20) %><%= p.profile.first_name %>&nbsp<%= p.profile.last_name %></b><%= link_to "Confirm", user_friend_path( :user_id => current_user, :friend_id => p), :method => :put, :class => "accept" %><%= link_to "Deny", user_friend_path( :user_id => current_user.id, :friend_id => p), :method => :delete, :class => "deny" %></li>
  <% end %> 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>SocialNetwork</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "vendor",    :media => "all" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "vendor" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <div class="wrapper">
   <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert-#{key}") %>
    <% end %>
    <%= yield %>
  </div>
  <script>

  </script>
</body>
</html>